### ISSUE TITLE
Module parse failed: Unexpected token (22:11)

### ISSUE THREAD

**Issue by zhishaofei3** [bjarneo/nanon#13]
nanon index.js index.min.js --name=MyClock
⊷ Bundling library...Some errors occured:
./index.js
Module parse failed: Unexpected token (22:11)
You may need an appropriate loader to handle this file type.
|   render(props, state) {
|     let time = new Date(state.time).toLocaleTimeString();
|     return <span>{ time }</span>;
|   }
| }
✖ :(

**Comment by bjarneo** [comment]
I would suggest you to use https://github.com/developit/microbundle instead. This project has not been maintained for years. I have to update the readme letting people know. Awesome you found it and wanted to use it though :)
